# Generated by Django 6.0.3 on 2026-03-17 13:06

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.CharField(help_text='Short description', max_length=200)),
                ('full_description', models.TextField()),
                ('programs', models.JSONField(default=list, help_text='["Nursery", "Primary P.1-P.7", etc.]')),
                ('campus_type', models.CharField(choices=[('day', 'Day Only'), ('boarding', 'Boarding Only'), ('both', 'Both Day & Boarding')], default='both', max_length=20)),
                ('facilities', models.JSONField(default=list, help_text='["Modern Classrooms", "Library", etc.]')),
                ('established', models.CharField(default='2013', max_length=10)),
                ('image', models.ImageField(upload_to='campuses/')),
                ('icon', models.CharField(default='🏛️', max_length=10)),
                ('student_count', models.CharField(default='450+', max_length=20)),
                ('staff_count', models.CharField(default='50+', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Campuses',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji icon (e.g., 🤝, ⭐, 🏆)', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Begin Your Journey Today', max_length=200)),
                ('text', models.TextField(default='Join a community where every learner thrives across our four specialized campuses')),
                ('year_text', models.CharField(default='Applications Open for 2026—27', max_length=100)),
                ('background_image', models.ImageField(upload_to='cta/')),
                ('primary_button_text', models.CharField(default='Apply Now', max_length=50)),
                ('primary_button_link', models.CharField(default='/admissions/apply', max_length=200)),
                ('secondary_button_text', models.CharField(default='Request Information', max_length=50)),
                ('secondary_button_link', models.CharField(default='/contact', max_length=200)),
                ('features', models.JSONField(default=list, help_text='["Quality Education", "Strong Values", "Holistic Development"]')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'CTA Section',
            },
        ),
        migrations.CreateModel(
            name='HeroSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(help_text='Campus name or location', max_length=100)),
                ('image', models.ImageField(upload_to='hero_slides/')),
                ('overlay_color', models.CharField(default='linear-gradient(135deg, rgba(10,26,47,0.7) 0%, rgba(26,43,76,0.5) 100%)', max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Slide',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(help_text='Emoji icon (e.g., 📚, 👨\u200d🏫, 🏫)', max_length=10)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typing_texts', models.JSONField(default=list, help_text='["Oasis Schools Arua", "Main Campus", "Muni Campus", etc.]')),
                ('auto_rotate_speed', models.PositiveIntegerField(default=3500, help_text='Hero slide rotation speed in milliseconds')),
                ('testimonials_auto_play_speed', models.PositiveIntegerField(default=4000)),
                ('enable_parallax', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('value', models.PositiveIntegerField()),
                ('suffix', models.CharField(blank=True, default='+', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('trend', models.CharField(blank=True, max_length=100)),
                ('icon', models.CharField(choices=[('Users', 'Users'), ('Award', 'Award'), ('TrendingUp', 'Trending Up'), ('GraduationCap', 'Graduation Cap'), ('BookOpen', 'Book Open'), ('MapPin', 'Map Pin')], default='Users', max_length=20)),
                ('color', models.CharField(default='#1a2b4c', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='WelcomeSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(default='Welcome to Oasis', max_length=100)),
                ('title', models.CharField(default='Nurturing Young Minds, Building Futures', max_length=200)),
                ('description_paragraphs', models.JSONField(default=list, help_text='["First paragraph", "Second paragraph"]')),
                ('image', models.ImageField(upload_to='welcome/')),
                ('image_caption', models.CharField(blank=True, max_length=200)),
                ('learn_more_link', models.CharField(default='/about', max_length=200)),
                ('vision_text', models.TextField()),
                ('mission_text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Welcome Section',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('date_display', models.CharField(help_text="e.g., 'MAR 20'", max_length=20)),
                ('time', models.CharField(help_text="e.g., '8:00 AM - 4:00 PM'", max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='events/')),
                ('description', models.TextField(blank=True)),
                ('is_upcoming', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='website.campus')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('academics', 'Academics'), ('sports', 'Sports'), ('arts', 'Arts'), ('events', 'Events')], max_length=20)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='gallery/thumbnails/')),
                ('photographer', models.CharField(default='Oasis Schools', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gallery_images', to='website.campus')),
            ],
            options={
                'verbose_name_plural': 'Gallery Images',
                'ordering': ['-is_featured', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('quote', models.TextField()),
                ('image', models.ImageField(upload_to='testimonials/')),
                ('rating', models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='website.campus')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
