# Generated by Django 5.2.14 on 2026-05-14 19:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('announcement', 'Announcement'), ('event', 'Event'), ('campus_update', 'Campus Update'), ('achievement', 'Achievement'), ('notice', 'Notice'), ('academic', 'Academic'), ('sports', 'Sports'), ('arts', 'Arts & Culture')], default='announcement', max_length=50)),
                ('excerpt', models.TextField(help_text='Short summary displayed on news listing page', max_length=300)),
                ('content', models.TextField(help_text='Full news article content')),
                ('featured_image', models.ImageField(help_text='Main image for the news article', upload_to='news/featured/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='news/thumbnails/')),
                ('author', models.CharField(default='Oasis Schools Admin', max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('published_date', models.DateField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage featured section')),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.TextField(blank=True, max_length=500)),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_articles', to='website.campus')),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-published_date', '-is_featured', 'order'],
            },
        ),
    ]
