# Generated by Django 5.2.14 on 2026-05-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='About Our School', max_length=200)),
                ('hero_subtitle', models.CharField(default='Model Islamic & City Model Schools - Excellence in Education', max_length=500)),
                ('hero_badge_text', models.CharField(default='بسم الله الرحمن الرحيم', max_length=100)),
                ('hero_background_image', models.ImageField(blank=True, null=True, upload_to='about/hero/')),
                ('info_card_1_title', models.CharField(default='Our Location', max_length=100)),
                ('info_card_1_text', models.CharField(default='Former TAWAKAL PRIMARY SCHOOL, Pangsha Ward, Arua', max_length=200)),
                ('info_card_2_title', models.CharField(default='Established', max_length=100)),
                ('info_card_2_text', models.CharField(default='2008', max_length=100)),
                ('info_card_3_title', models.CharField(default='Our Motto', max_length=100)),
                ('info_card_3_text', models.CharField(default='Excellence is our pride', max_length=200)),
                ('cta_title', models.CharField(default='Join Our Learning Community', max_length=200)),
                ('cta_text', models.CharField(default='Give your child the gift of quality Islamic education', max_length=500)),
                ('cta_button_text', models.CharField(default='Apply for Admission', max_length=50)),
                ('cta_button_link', models.CharField(default='/admissions/apply', max_length=200)),
                ('cta_secondary_button_text', models.CharField(default='Contact Us', max_length=50)),
                ('cta_secondary_button_link', models.CharField(default='/contact', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Page Settings',
                'verbose_name_plural': 'About Page Settings',
            },
        ),
        migrations.CreateModel(
            name='HistoryMilestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='LeadershipMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('qualification', models.CharField(blank=True, max_length=200)),
                ('experience', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField()),
                ('image', models.ImageField(upload_to='leadership/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Leadership Members',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='MissionVision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('mission', 'Mission'), ('vision', 'Vision')], max_length=10)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('points', models.JSONField(default=list, help_text='List of key points')),
                ('icon', models.CharField(default='Target', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Mission & Vision',
            },
        ),
        migrations.CreateModel(
            name='SchoolStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('label', models.CharField(max_length=100)),
                ('icon', models.CharField(default='Users', max_length=50)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'School Statistics',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='corevalue',
            name='arabic_name',
            field=models.CharField(blank=True, help_text='Arabic translation', max_length=100),
        ),
        migrations.AddField(
            model_name='corevalue',
            name='color',
            field=models.CharField(default='#10B981', max_length=20),
        ),
        migrations.AlterField(
            model_name='corevalue',
            name='icon',
            field=models.CharField(default='Shield', max_length=50),
        ),
    ]
