# Generated by Django 6.0.3 on 2026-03-17 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('main', 'Main Campus - Abirichi'), ('muni', 'Muni Campus - Muni'), ('annex', 'Annex Campus - Arua'), ('golden', 'Golden Brain - Koboko'), ('all', 'All Campuses')], default='all', max_length=20)),
                ('program', models.CharField(max_length=50)),
                ('requirements', models.TextField()),
                ('documents_needed', models.JSONField(default=list)),
                ('age_requirement', models.CharField(blank=True, max_length=100)),
                ('academic_requirement', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campus', models.CharField(choices=[('main', 'Main Campus - Abirichi'), ('muni', 'Muni Campus - Muni'), ('annex', 'Annex Campus - Arua'), ('golden', 'Golden Brain - Koboko'), ('all', 'All Campuses')], max_length=20)),
                ('program', models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary School'), ('vocational', 'Vocational Programs')], max_length=20)),
                ('grade_level', models.CharField(max_length=50)),
                ('tuition_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('boarding_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('other_fees', models.JSONField(blank=True, default=dict)),
                ('academic_year', models.CharField(default='2026-27', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['campus', 'program', 'grade_level'],
            },
        ),
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('campus', models.CharField(blank=True, max_length=100)),
                ('program', models.CharField(blank=True, max_length=100)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('campus', models.CharField(choices=[('main', 'Main Campus - Abirichi'), ('muni', 'Muni Campus - Muni'), ('annex', 'Annex Campus - Arua'), ('golden', 'Golden Brain - Koboko')], max_length=20)),
                ('program', models.CharField(choices=[('nursery', 'Nursery'), ('primary', 'Primary School'), ('vocational', 'Vocational Programs')], max_length=20)),
                ('grade_level', models.CharField(max_length=50)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='applications/birth_certificates/')),
                ('previous_school_records', models.FileField(blank=True, null=True, upload_to='applications/school_records/')),
                ('passport_photo', models.ImageField(blank=True, null=True, upload_to='applications/photos/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewing', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.RemoveField(
            model_name='application',
            name='applying_for',
        ),
        migrations.RemoveField(
            model_name='applicationstatus',
            name='application',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='FAQ',
        ),
        migrations.DeleteModel(
            name='ImportantDate',
        ),
        migrations.DeleteModel(
            name='Requirement',
        ),
        migrations.DeleteModel(
            name='Testimonial',
        ),
        migrations.DeleteModel(
            name='Program',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
        migrations.DeleteModel(
            name='ApplicationStatus',
        ),
    ]
