# Generated by Django 6.0.3 on 2026-03-19 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_admissionrequirement_feestructure_inquiry_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_ref', models.CharField(max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('nationality', models.CharField(default='Ugandan', max_length=50)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('alternative_phone', models.CharField(blank=True, max_length=15)),
                ('address', models.TextField(blank=True)),
                ('district', models.CharField(default='Arua', max_length=50)),
                ('father_name', models.CharField(blank=True, max_length=200)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('father_phone', models.CharField(blank=True, max_length=15)),
                ('father_email', models.EmailField(blank=True, max_length=254)),
                ('mother_name', models.CharField(blank=True, max_length=200)),
                ('mother_occupation', models.CharField(blank=True, max_length=100)),
                ('mother_phone', models.CharField(blank=True, max_length=15)),
                ('mother_email', models.EmailField(blank=True, max_length=254)),
                ('guardian_name', models.CharField(blank=True, max_length=200)),
                ('guardian_relation', models.CharField(blank=True, max_length=50)),
                ('guardian_phone', models.CharField(blank=True, max_length=15)),
                ('guardian_email', models.EmailField(blank=True, max_length=254)),
                ('emergency_name', models.CharField(max_length=200)),
                ('emergency_relation', models.CharField(max_length=50)),
                ('emergency_phone', models.CharField(max_length=15)),
                ('campus', models.CharField(choices=[('main', 'Main Campus - Abirichi'), ('annex', 'Annex Campus - Arua'), ('muni', 'Muni Campus'), ('golden-brain', 'Golden Brain - Koboko')], max_length=20)),
                ('program', models.CharField(choices=[('early-childhood', 'Early Childhood'), ('primary', 'Primary School'), ('secondary', 'Secondary School'), ('vocational', 'Vocational Programs')], max_length=20)),
                ('applying_for', models.CharField(max_length=50)),
                ('intake', models.CharField(max_length=20)),
                ('term', models.CharField(default='term1', max_length=10)),
                ('boarding_status', models.CharField(default='day', max_length=10)),
                ('previous_school', models.CharField(blank=True, max_length=200)),
                ('previous_school_address', models.TextField(blank=True)),
                ('last_class', models.CharField(blank=True, max_length=50)),
                ('last_class_grade', models.CharField(blank=True, max_length=50)),
                ('reason_for_transfer', models.TextField(blank=True)),
                ('has_special_needs', models.BooleanField(default=False)),
                ('special_needs_details', models.TextField(blank=True)),
                ('medical_conditions', models.TextField(blank=True)),
                ('how_did_you_hear', models.CharField(blank=True, max_length=50)),
                ('additional_notes', models.TextField(blank=True)),
                ('birth_certificate', models.FileField(blank=True, null=True, upload_to='applications/documents/')),
                ('passport_photo', models.FileField(blank=True, null=True, upload_to='applications/photos/')),
                ('last_report_card', models.FileField(blank=True, null=True, upload_to='applications/reports/')),
                ('transfer_letter', models.FileField(blank=True, null=True, upload_to='applications/transfers/')),
                ('medical_report', models.FileField(blank=True, null=True, upload_to='applications/medical/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('waitlisted', 'Waitlisted')], default='pending', max_length=20)),
                ('review_notes', models.TextField(blank=True)),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_application', 'New Application'), ('status_change', 'Status Change'), ('document_upload', 'Document Upload'), ('interview_scheduled', 'Interview Scheduled'), ('payment_received', 'Payment Received')], max_length=20)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='admissions.admissionapplication')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='StudentApplication',
        ),
        migrations.AlterModelOptions(
            name='feestructure',
            options={},
        ),
        migrations.RenameField(
            model_name='admissionrequirement',
            old_name='requirements',
            new_name='requirement',
        ),
        migrations.RenameField(
            model_name='feestructure',
            old_name='grade_level',
            new_name='class_level',
        ),
        migrations.RenameField(
            model_name='feestructure',
            old_name='registration_fee',
            new_name='total_fees',
        ),
        migrations.RemoveField(
            model_name='admissionrequirement',
            name='documents_needed',
        ),
        migrations.RemoveField(
            model_name='admissionrequirement',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='campus',
        ),
        migrations.RemoveField(
            model_name='inquiry',
            name='program',
        ),
        migrations.AddField(
            model_name='admissionrequirement',
            name='additional_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admissionrequirement',
            name='documents_required',
            field=models.TextField(default=1, help_text='List of required documents'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='inquiry_type',
            field=models.CharField(choices=[('general', 'General Inquiry'), ('admission', 'Admission Inquiry'), ('fee', 'Fee Structure'), ('program', 'Program Information'), ('other', 'Other')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inquiry',
            name='responded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='responded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='response',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='admissionrequirement',
            name='campus',
            field=models.CharField(choices=[('main', 'Main Campus - Abirichi'), ('annex', 'Annex Campus - Arua'), ('muni', 'Muni Campus'), ('golden-brain', 'Golden Brain - Koboko'), ('all', 'All Campuses')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='academic_year',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='campus',
            field=models.CharField(choices=[('main', 'Main Campus - Abirichi'), ('annex', 'Annex Campus - Arua'), ('muni', 'Muni Campus'), ('golden-brain', 'Golden Brain - Koboko')], max_length=20),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='other_fees',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='feestructure',
            name='program',
            field=models.CharField(choices=[('early-childhood', 'Early Childhood'), ('primary', 'Primary School'), ('secondary', 'Secondary School'), ('vocational', 'Vocational Programs')], max_length=20),
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterUniqueTogether(
            name='feestructure',
            unique_together={('campus', 'program', 'class_level', 'academic_year')},
        ),
    ]
