# Generated by Django 6.0.3 on 2026-03-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0003_admissionapplication_applicationnotification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionapplication',
            name='agree_to_terms',
            field=models.BooleanField(default=False, help_text='Applicant agreed to terms and conditions'),
        ),
    ]
